### ISSUE TITLE
1.11.2-0.2.9 crashes client on startup in forge 2223

### ISSUE THREAD

**Issue by kreezxil** [AtomicBlom/HomecraftMineware#8]
http://pastebin.com/DjpmRHp2

**Comment by kreezxil** [comment]
thought maybe it was forge, so i updated to 2224 same crash

http://pastebin.com/kUqt7JPW

**Comment by AtomicBlom** [comment]
based on this line of your crash:
`Caused by: java.io.FileNotFoundException: G:\Documents\Curse\Minecraft\Instances\morpheus!! (The system cannot find the file specified)`
I'm going to hazard a guess that it doesn't like the name of your modpack. I think Exclamation marks have a special meaning for Java.

I don't think I can do anything to fix this. Try renaming your modpack and see if that fixes the issue (or at least gives a different error.

**Comment by AtomicBlom** [comment]
I haven't heard back on this, closing for now.
